openapi: 3.0.0
info:
  title: My Service
  version: 1.0.0
# Add this line here to disable OAuth2 globally
x-wso2-disable-security: true 
paths:
  /users:
    get:
      summary: Get users
      # Or add it here to disable it ONLY for this specific endpoint
      x-wso2-disable-security: true
      responses:
        '200':
          description: OK